### This script performs a PCA (R-verified)

In [1]:
%load_ext rpy2.ipython
%config InlineBackend.figure_format = 'retina'

import pandas as pd
from sklearn.decomposition import FactorAnalysis
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import numpy as np

import warnings
warnings.filterwarnings('ignore')

#### set directory and import dataset

In [2]:
datadir = '/Volumes/Maxtor/phdresearch/som_new/'
outdir = '/Volumes/Maxtor/phdresearch/som_new/'

In [3]:
data = pd.read_csv(datadir + 'SAfr_700hpa_era_newAB.csv',names = ['0,0','0,1','0,2','1,0','1,1','1,2','2,0','2,1','2,2','3,0','3,1'
         ,'3,2','MEI_AVG','AAO_AVG','ITCZInt_AVG','MJO_AVG','DMI_AVG'])

#### select specific columns in dataset

In [4]:
df = data.iloc[:,0:15]

In [5]:
type(df); df.head()

0,0  0,1  0,2  1,0  1,1  1,2  2,0  2,1  2,2  3,0  3,1  3,2  MEI_AVG  \
JFM80    0    0    6    0    5    9    8    5   13   12   20   13    0.652   
FMA80    0    2    6    4    6   13    7    5    9   11   16   11    0.729   
MAM80    8    9   10    7    3   12    6    6    8    8    8    7    0.853   
AMJ80   15   15    9    9    6   13    6    6    5    6    0    1    0.925   
MJJ80   15   15   20    6    7   16    3    5    5    0    0    0    0.872   

       AAO_AVG  ITCZInt_AVG  
JFM80   -0.950        6.093  
FMA80   -1.491        6.427  
MAM80   -1.324        6.113  
AMJ80   -0.754        5.903  
MJJ80   -0.712        6.273

#### extract values at each node of the SOM frequency dataset

In [6]:
nodes = ['0,0','0,1','0,2','1,0','1,1','1,2','2,0','2,1','2,2','3,0','3,1'
         ,'3,2','MEI_AVG','AAO_AVG','ITCZInt_AVG']

## Separating out the nodes
x = df.loc[:, nodes].values

# Standardizing the nodes
x = StandardScaler().fit_transform(x)

In [7]:
type (x); x.shape      #x type is a numpy array

(406, 15)

#### perform factor analysis with varimax rotation

In [8]:
n_comps = 3

In [66]:
fan = FactorAnalysis(n_components=n_comps, rotation='varimax').fit(x)

In [67]:
fan.get_covariance();

In [68]:
fan.components_.T
-0.81229198 -0.05672762  0.01706003 

array([[-0.81502447, -0.03480992,  0.02812297],
       [-0.82913934,  0.11197453,  0.19759255],
       [-0.68419625,  0.36594673,  0.29815912],
       [-0.6794119 ,  0.05111988, -0.28662233],
       [-0.30974335,  0.4438227 , -0.29076044],
       [-0.00837923,  0.72039307,  0.03095742],
       [-0.11678019, -0.09102721, -0.68182675],
       [ 0.4544653 ,  0.09565417, -0.4286571 ],
       [ 0.66459206,  0.2858315 ,  0.19576088],
       [ 0.54842232, -0.55911666, -0.10681822],
       [ 0.73261859, -0.48129461,  0.19716769],
       [ 0.74314022, -0.2576395 ,  0.29560811],
       [-0.23096913,  0.54929702,  0.0923048 ],
       [ 0.06120481, -0.06960255,  0.23025851],
       [ 0.09859103, -0.19750385, -0.0816199 ]])

In [69]:
fan_scores = fan.transform(x)

In [70]:
fan_scores

array([[ 1.1561915 , -0.06021044,  0.42288537],
       [ 0.84491527,  0.17611087,  0.12229212],
       [-0.00716542,  0.13258153,  0.31981211],
       ...,
       [-1.52939638, -0.68713567, -0.45890216],
       [-0.86959885, -0.47687711, -0.38361965],
       [ 0.24000241,  0.28792126, -0.3996681 ]])

In [71]:
df_scores = pd.DataFrame(fan_scores,columns = ['RC1', 'RC2','RC3'])
df_scores

RC1       RC2       RC3
0    1.156191 -0.060210  0.422885
1    0.844915  0.176111  0.122292
2   -0.007165  0.132582  0.319812
3   -0.766558  0.268395  0.047018
4   -0.901574  0.825561  0.736015
5   -0.679149  1.189052  0.916992
6   -0.630750  0.894283  0.483377
7   -1.006724  0.040748  0.280071
8   -0.740854 -0.348403 -1.077929
9   -0.009384 -0.601458 -0.970929
10   0.605337 -0.572052 -1.754807
11   1.052212 -0.949708 -0.181153
12   1.201719 -0.484352  0.139542
13   1.318652 -0.315267  0.654149
14   0.878787  0.053229 -0.033957
15  -0.038200  0.004654 -0.481832
16  -0.714040 -0.369275 -0.960313
17  -0.958986 -0.443860 -1.647119
18  -0.766878 -0.666025 -1.595422
19  -0.371536 -0.317792 -1.877259
20   0.109308 -0.108617 -1.645994
21   0.753991  0.289382 -1.696287
22   1.068474 -0.308546 -0.871002
23   1.255628 -1.033380  0.290672
24   1.275816 -1.365044  0.972736
25   1.185759 -0.847411  0.730952
26   0.656202  0.115447 -0.520004
27  -0.478169 -0.005541 -0.645255
28  -0.719218  0.472195 -0.546863
29  -1.059144  0.225582  0.338618
..        ...       ...       ...
376 -0.224344  0.124323 -1.440372
377 -0.229209  0.046643 -1.258213
378 -0.590703 -0.093934 -0.078989
379 -0.932831 -0.931978 -0.513369
380 -0.707477 -1.249752 -1.113402
381  0.391204 -1.048604 -1.682425
382  0.755488 -0.996164 -0.901753
383  1.035764 -1.464957  0.095764
384  0.973437 -1.219065  0.487493
385  0.935108 -0.406790  0.224354
386  0.147480  0.392697  0.292129
387 -0.621662  0.343391  0.080971
388 -1.077070 -0.114089 -0.510202
389 -1.394117 -0.735208 -0.792508
390 -1.717423 -1.142863 -0.133099
391 -1.532328 -1.084811  0.406728
392 -0.622148 -0.010696 -0.279190
393  0.684919  0.225241 -0.822094
394  0.836447  0.451096 -0.703400
395  0.958161 -0.183507  0.097520
396  0.719898  0.667919  0.532785
397  0.576842  0.846532  0.632510
398 -0.311805  0.992195  0.854342
399 -1.267907  0.055978  0.533156
400 -1.768081 -0.693956  0.551283
401 -1.650335 -1.067270 -0.319055
402 -1.737664 -1.318632 -0.456815
403 -1.529396 -0.687136 -0.458902
404 -0.869599 -0.476877 -0.383620
405  0.240002  0.287921 -0.399668

[406 rows x 3 columns]

#### sanity check --- perform pca from first principles using numpy

In [15]:
eigvals, eigvecs = np.linalg.eig(np.cov(x.T))
factors = (np.sqrt(eigvals) * eigvecs)[:, :n_comps]
print(factors)

[[-0.77793312  0.30714889  0.25604422]
 [-0.82045337  0.07283559  0.35008235]
 [-0.77649269 -0.28713084  0.30414943]
 [-0.70880852  0.37084436 -0.0736359 ]
 [-0.50491111 -0.09636458 -0.52420846]
 [-0.28842885 -0.70739083 -0.33173586]
 [-0.11407354  0.55018214 -0.60418794]
 [ 0.4170387   0.02530657 -0.65685081]
 [ 0.53831704 -0.62420616 -0.09162505]
 [ 0.75550438  0.35455099  0.06331131]
 [ 0.89577883  0.06770724  0.24102826]
 [ 0.81625093 -0.17773774  0.21855766]
 [-0.46026671 -0.52954658 -0.19856932]
 [ 0.14600456 -0.11260309  0.4030715 ]
 [ 0.20441316  0.31022392 -0.13708812]]


In [72]:
rotated = fa._ortho_rotation(factors[:, :n_comps], method='varimax').T
rotated

array([[-0.87342606, -0.01131561,  0.04558394],
       [-0.84409682, -0.17208279,  0.24268181],
       [-0.65391979, -0.45054467,  0.38378419],
       [-0.75328167, -0.0719827 , -0.26970821],
       [-0.27719737, -0.5339026 , -0.42086281],
       [ 0.10277552, -0.82451238,  0.05708062],
       [-0.16124463,  0.11346991, -0.80117475],
       [ 0.52630313, -0.07048493, -0.56925528],
       [ 0.74232505, -0.27439412,  0.24794173],
       [ 0.51601767,  0.65136374, -0.09976291],
       [ 0.70649641,  0.57043296,  0.20141416],
       [ 0.73688283,  0.3337475 ,  0.30205965],
       [-0.15222862, -0.70875896,  0.07862562],
       [ 0.07086393,  0.15382973,  0.4096073 ],
       [ 0.09562399,  0.27590965, -0.26748213]])

#### create a dataframe from rotated principal compnents

In [17]:
principalDf = pd.DataFrame(data = rotated, columns = ['RC1', 'RC2','RC3'])

In [18]:
principalDf.rename(index={0:'0,0',1:'0,1',2:'0,2',3:'1,0',4:'1,1',5:'1,2',
                         6:'2,0',7:'2,1',8:'2,2',9:'3,0',10:'3,1',11:'3,2',
                         12:'MEI_AVG',13:'AAO_AVG',14:'ITCZInt_AVG'}, inplace=True)


In [19]:
principalDf

RC1       RC2       RC3
0,0         -0.873426 -0.011316  0.045584
0,1         -0.844097 -0.172083  0.242682
0,2         -0.653920 -0.450545  0.383784
1,0         -0.753282 -0.071983 -0.269708
1,1         -0.277197 -0.533903 -0.420863
1,2          0.102776 -0.824512  0.057081
2,0         -0.161245  0.113470 -0.801175
2,1          0.526303 -0.070485 -0.569255
2,2          0.742325 -0.274394  0.247942
3,0          0.516018  0.651364 -0.099763
3,1          0.706496  0.570433  0.201414
3,2          0.736883  0.333748  0.302060
MEI_AVG     -0.152229 -0.708759  0.078626
AAO_AVG      0.070864  0.153830  0.409607
ITCZInt_AVG  0.095624  0.275910 -0.267482

#### sanity check----verifying PCA with R

In [74]:
%Rpush factors
%Rpush x
%Rpush n_comps

In [75]:
%%R

a = varimax(factors, normalize=T, eps=1e-6)

In [78]:
%%R
unclass(a$loadings)

             [,1]        [,2]        [,3]
 [1,] -0.86984524 -0.08660903  0.03077592
 [2,] -0.82815218 -0.27418523  0.19998206
 [3,] -0.61670302 -0.55601030  0.29735806
 [4,] -0.74480301 -0.08624015 -0.28842404
 [5,] -0.23336861 -0.47928070 -0.50482173
 [6,]  0.16774412 -0.81239927 -0.07423613
 [7,] -0.16855012  0.22785739 -0.77487296
 [8,]  0.53107547  0.06322529 -0.56566430
 [9,]  0.76137772 -0.25191756  0.21131783
[10,]  0.46289237  0.69717920  0.01316891
[11,]  0.65874325  0.58399639  0.30017353
[12,]  0.70765234  0.33731170  0.36203966
[13,] -0.09566693 -0.72186866 -0.03805631
[14,]  0.05783814  0.09103560  0.42991940
[15,]  0.07384082  0.32192952 -0.21846211


In [ ]:
#help(FactorAnalysis);

In [2]:
#%%R

#print(psych::principal(X, rotate="varimax", nfactors=3, scores=TRUE,
#                       covar=TRUE)$loadings)

In [1]:
#%%R
#install.packages('psych',dep =T)